### ISSUE TITLE
tec_UFOUNDED_PAYMENT

### ISSUE THREAD

**Issue by fmSterio** [GateHubNet/microkit#13]
Since I was just testing how it works the gateHub as a new user, I've faced this error message with: tec_UFOUNDED_PAYMENT it seems as a name of a variable exposed on the message. 

![screen shot 2017-04-04 at 12 20 38 am](https://cloud.githubusercontent.com/assets/18398505/24634375/e8d742d8-18cd-11e7-83b0-833e67e00bd3.png)

My wallet address: rEfJMTHSEL3HKZbBsNpWm5oq11tnDhiBrM

**Comment by offlinehacker** [comment]
Hi, thanks for your report, but this message is intentionally shown, as this is ripple error, that your client(your browser) gets when sending payment to ripple. Your browser is sending payments directly to ripple network if you are using ripple wallet and does not call any gatehub api-s. Since this repository has nothing to do with gatehub wallet application, I'm closing it. If you have or will have any additional questions, please feel free to send them to support@gatehub.net, where our nice support team, will answer them. We currently do not have any public issue tracker, but we are working on having one soon.
